networks:
  fastfoodnetwork:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: dbfastfood
    restart: unless-stopped
    volumes:
      - ./infrastructure/persistence/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    networks:
      - fastfoodnetwork

  fastfoodapp:
    image: wellingt0npires/fastfood:latest
    ports:
      - "8080:8080"
    networks:
      - fastfoodnetwork