apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: fastfoodapp
  name: fastfoodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastfoodapp
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/fast-food-tech-challenge-fastfoodnetwork: "true"
        io.kompose.service: fastfoodapp
    spec:
      containers:
        - image: wellingt0npires/fastfood:latest
          name: fastfoodapp
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
      restartPolicy: Always
